# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Native App Testing Self Hosted Distributed

on:
  workflow_dispatch:
    inputs:
      run_environment:
        description: 'The device or browser platform on which the test runs'
        required: true
        type: choice
        options:
          - 'android_farm_device'
          - 'ios_farm_device'
          - 'android_device'
        default: 'android_farm_device'
      app_environment:
        description: 'The app environment on which to run tests'
        required: true
        default: 'qa'
        type: choice
        options:
          - 'qa'
          - 'dev'
          - 'prod'
      publish_results:
        description: 'Do you want to publish results'
        required: true
        default: false
        type: boolean
      install_java:
        description: 'Install Java on Runner'
        required: true
        default: false
        type: boolean


jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        feature: [ home,login,sort ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        #        if: ${{ github.event.inputs.install_java == 'true'}}
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        continue-on-error: true
        run: mvn -B clean verify -Denvironment=${{ github.event.inputs.run_environment }} -DappEnvName=${{ github.event.inputs.app_environment }} -Dcucumber.features=src/test/resources/features/app/${{ matrix.feature }}
      - name: Upload Test results
        #        if: ${{ github.event.inputs.publish_results == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results ${{ matrix.feature }}
          path: |
            target/site/serenity/serenity-summary.html
#            target/site/serenity/index.html

